### ISSUE TITLE
Compile incorrectly 夫「某物」之「「某術」」。施其。

### ISSUE THREAD

**Issue by cuixiping** [antfu/wenyan-lang-vscode#10] opened 2019-12-28 11:07 UTC
```
夫「某物」之「「某術」」。施其。
```
Compile result from vscode includes **`undefined`**:
```
var _ans1 = 某物["某術"]
var _ans2 = undefined()
```

But the compile result by online IDE is:
```
var _ans1 = 某物["某術"];
var _ans2 = _ans1();
```

**Comment by antfu** [comment] 2019-12-29 04:49
This is probably due the versions difference used for online IDE and integrated compiler. (Online IDE is always reflect to master branch whatever npm package version is). This might get fixed on the next release.
https://github.com/LingDong-/wenyan-lang/pull/416

**Comment by antfu** [comment] 2019-12-31 10:06
Looks like the problem is gone.
![image](https://user-images.githubusercontent.com/11247099/71617908-4c49a500-2bf8-11ea-9459-aabdbe98c930.png)

**Comment by cuixiping** [comment] 2019-12-31 10:45
Great!

**Closed** 2019-12-31 10:45 UTC
